### ISSUE TITLE
[MPI_WP2]: 6. BMSC app: data export

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/bmsc-app#10]
Save all results in an Excel or ODT file:

- Model evaluation: for the different models across different rows show and in separate columns the value for all “Information / Cross-Validation Error criterion” 
-  In a separate sheet show Model summary for each model (separated by empty rows) 
- In a separate sheet show the different models across different rows show and in separate columns the Diagnostic results (adjust this for the fact that each diagnostic requires a different number of rows) 
- Show in a separate sheet the Durbi-Watson text result 
- Show in a separate sheet the results for option global under “Variable importance” and for each model for option “model based” 

For global option “Variable importance type” show the regression sign of the coefficients associated to each variable (to be displayed in separate columns as “1” or “-1”). There should be a sign column for each model. The name of each column is the full regression model (as available under Model summary)

**Comment by arunge** [comment]
@isomemo The features mentioned [above](https://github.com/Pandora-IsoMemo/bmsc-app/issues/10#issue-1334355492) (1) are now online on [BMSCapp beta](https://isomemoapp.com/app/bmsc-beta) with [version 24.04.1](https://github.com/Pandora-IsoMemo/bmsc-app/pull/31) and ready for testing.

![image](https://github.com/Pandora-IsoMemo/bmsc-app/assets/16759098/6825e62e-8ddb-48bf-a664-36d415e79d06)


Please feel free to give feedback.
