### ISSUE TITLE
Issue with import module

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bmsc-app#18]
@arunge I created a SQL query via the import data module. It worked. I checked some of the BMSC tabs and then returned to the one for the import data. The app crashed. I suspect the same will happen to other apps.

**Comment by isomemo** [comment]
@arunge Ok for now!

**Comment by isomemo** [comment]
@arunge creation looks Ok! But I need to test Operations to be certain this is working well!

One thing I did notice is that there is no Type information being given (I tried the rectangle option)

**Comment by arunge** [comment]
> @arunge creation looks Ok! But I need to test Operations to be certain this is working well!
> 
> One thing I did notice is that there is no Type information being given (I tried the rectangle option)

@isomemo Doesn't this comment belong to the issue?
- https://github.com/Pandora-IsoMemo/iso-app/issues/19
