### ISSUE TITLE
BMSC App is down

### ISSUE THREAD

**Issue by mgross** [Pandora-IsoMemo/bmsc-app#3]
@wahani @jroachell15 
The App is not reachable anymore (was previously available under https://isomemoapp.com/app/constraint-estimation-app-beta). Could you check this?

**Comment by arunge** [comment]
@mgross the app has moved to: https://isomemoapp.com/app/bmsc-beta :slightly_smiling_face: 
and is currently running:
![image](https://user-images.githubusercontent.com/16759098/158884240-bb19d526-43e9-4957-afe0-614fe644990a.png)
