### ISSUE TITLE
Loop bug

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/bmsc-app#9]
I loaded the attached Excel file:
[Autotroph AA d15N.xlsx](https://github.com/Pandora-IsoMemo/bmsc-app/files/8879891/Autotroph.AA.d15N.xlsx)
.

Under "Variable Correlations" I selected the variables corresponding to columns starting at BG until DF. The app entered in a strange loop behaviour and an error was issued. See this video: https://youtu.be/Hsek_QrGHOY

This may be related with the fact that cells with no data have a "nd" text entry.

**Comment by arunge** [comment]
This issue was fixed with:
- https://github.com/Pandora-IsoMemo/bmsc-app/pull/26
